services:

  mysql:
    image: mysql
    container_name: empreendenow_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: "empreendenow_db"
    ports:
      - "3308:3306"

  Api:
    build:
      context: ./EmpreendeNow-API
      dockerfile: Dockerfile
    container_name: empreendenow-api
    image: empreendenow-api
    restart: always
    ports:
      - "4100:4100"
    depends_on:
      - mysql

  Web:
    build:
      context: ./EmpreendeNow-WEB
      dockerfile: Dockerfile  
    container_name: empreendenow-web
    image: empreendenow-web
    ports:
      - "4200:4200"
    depends_on:
      - Api

volumes:
  mysql_data:
